# fly.toml app configuration file generated for demo-face-recog-2 on 2025-03-17T15:16:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demo-face-recog-2'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
